# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl:
url: https://dloher.ch
last_modified_at: 2025-12-26
title: David Loher
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: Social Anthropologist PhD
tagline: David Loher, a social anthropologist and specialist in higher education development based in Switzerland.
description: Personal website of David Loher, a Switzerland-based social anthropologist and specialist in higher eduaction development.
author: David Loher
email: david.loher [at] posteo [dot] org
twitter:
  username: dloher
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: Europe/Zurich
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: src
# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path
#Plugins
plugins:
  - jekyll-seo-tag
#  - jekyll-sitemap
